document.addEventListener("DOMContentLoaded",()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const intro=$("#intro"),setup=$("#setupModal"),audio=$("#audio"),wave=$("#wave"),volume=$("#volumeSlider"),setupVolume=$("#setupVolume"),volumeToggle=$("#volumeToggle"),back=$("#musicBack"),pause=$("#musicPause"),skip=$("#musicSkip"),compareTimezone=$("#compareTimezone"),cursorSelect=$("#cursorSelect"),fullscreenToggle=$("#fullscreenToggle");
const tracks=[["Hoes Come Easy","FOREVER$TRONG"],["National Treasures","DRAKE"],["Low Life","FUTURE"],["Love Sosa","CHIEF KEEF"],["Stay Schemin","RICK ROSS"],["2055","SLEEPY HALLOW"],["Skin","OTUKA"]].map((x,i)=>({src:"./music/song"+(i+1)+".mp3",title:x[0],artist:x[1]}));
let entered=false,index=0,theme="matte",glow="MEDIUM",cursor="classic",backTimer=null; const localTimezone=Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC";
function recordView(){try{if(sessionStorage.getItem("nxr-view-recorded"))return;sessionStorage.setItem("nxr-view-recorded","1");const k="nxr-view-count",n=Number(localStorage.getItem(k)||2991)+1;localStorage.setItem(k,n);$("#viewCount").textContent=n.toLocaleString()}catch{}}
function apply(){document.body.className=document.body.className.replace(/theme-\w+|no-motion|no-led/g,"").replace(/\s+/g," ").trim()+" theme-"+theme;document.body.dataset.glow=glow;document.body.dataset.cursor=cursor;$("[data-theme]").forEach(b=>b.classList.toggle("selected",b.dataset.theme===theme));if($("#glowSelect"))$("#glowSelect").value=glow;if(cursorSelect)cursorSelect.value=cursor}
function render(){const t=tracks[index];$("#musicTitle").innerHTML=t.title+" <i>· "+t.artist+"</i>";$("#trackNumber").textContent=String(index+1).padStart(2,"0")+" / 07";$$(".track-choice").forEach((b,i)=>b.classList.toggle("selected",i===index));if(audio){audio.src=t.src;audio.load()}}
function build(){const box=$("#trackChoices");box.innerHTML=tracks.map((t,i)=>'<button class="track-choice" type="button" data-i="'+i+'"><span class="track-num">'+String(i+1).padStart(2,"0")+'</span><span><strong>'+t.title+'</strong><small>'+t.artist+'</small></span><b>›</b></button>').join("");box.addEventListener("click",e=>{const b=e.target.closest(".track-choice");if(b){index=+b.dataset.i;render()}})}
function openSetup(){if(entered)return;render();apply();setup.classList.add("open");setup.setAttribute("aria-hidden","false")}
function closeSetup(){setup.classList.remove("open");setup.setAttribute("aria-hidden","true")}
function formatTime(tz){return new Intl.DateTimeFormat([], {timeZone:tz,hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}).format(new Date())}
function offsetMinutes(tz,date=new Date()){const p=new Intl.DateTimeFormat("en-US",{timeZone:tz,timeZoneName:"longOffset",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(date),z=p.find(x=>x.type==="timeZoneName")?.value||"GMT",m=z.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/);return m?(m[1]==="-"?-1:1)*(+m[2]*60+(+(m[3]||0))):0}
function updateWorldClock(){const now=new Date(),name=$("#worldLocalName"),local=$("#worldLocalTime");if(name)name.textContent=localTimezone.replace(/^.*\//,"").replaceAll("_"," ");if(local)local.textContent=formatTime(localTimezone);$("[data-zone-time]").forEach(e=>e.textContent=formatTime(e.dataset.zoneTime));$("[data-zone-diff]").forEach(e=>{const mins=offsetMinutes(e.dataset.zoneDiff)-offsetMinutes(localTimezone,now),sign=mins>0?"+":mins<0?"−":"",abs=Math.abs(mins),h=Math.floor(abs/60),m=abs%60;e.textContent=mins===0?"SAME TIME":sign+h+"H"+(m?String(m).padStart(2,"0")+"M":"")+" VS YOU"});updateSetupTimezone()}
function updateSetupTimezone(){const l=$("#localTimezone"),d=$("#timezoneDifference"),t=$("#compareTime");if(l)l.textContent=localTimezone.replace(/^.*\//,"").replaceAll("_"," ");if(!compareTimezone||!d||!t)return;const tz=compareTimezone.value,mins=offsetMinutes(tz)-offsetMinutes(localTimezone),sign=mins>0?"+":mins<0?"−":"",abs=Math.abs(mins),h=Math.floor(abs/60),m=abs%60;d.textContent=mins===0?"SAME TIME":sign+h+"H"+(m?String(m).padStart(2,"0")+"M":"")+" VS YOU";t.textContent=formatTime(tz)}
function enter(){if(entered)return;entered=true;recordView();closeSetup();intro.classList.add("hide");document.body.classList.remove("locked");apply();audio.volume=+(volume.value||42)/100;audio.play().catch(()=>{});wave.classList.remove("paused")}
intro.onclick=()=>openSetup();
intro.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openSetup()}};
$("#enterExperience").onclick=enter;$("#closeSetup").onclick=closeSetup;$(".setup-backdrop").onclick=closeSetup;
$("#nextTrack").onclick=()=>{index=(index+1)%tracks.length;render()};$("#prevTrack").onclick=()=>{index=(index+tracks.length-1)%tracks.length;render()};
back?.addEventListener("click",e=>{e.stopPropagation();if(backTimer){clearTimeout(backTimer);backTimer=null;index=(index+tracks.length-1)%tracks.length;render();audio.play().catch(()=>{});return}audio.currentTime=0;audio.play().catch(()=>{});backTimer=setTimeout(()=>{backTimer=null},550)});
pause?.addEventListener("click",e=>{e.stopPropagation();if(audio.paused){audio.play().catch(()=>{});}else{audio.pause()}});skip?.addEventListener("click",e=>{e.stopPropagation();index=(index+1)%tracks.length;render();audio.play().catch(()=>{})});
$("[data-theme]").forEach(b=>b.onclick=()=>{theme=b.dataset.theme;apply()});$("#glowSelect").onchange=e=>{glow=e.target.value;apply()};compareTimezone?.addEventListener("change",updateSetupTimezone);cursorSelect?.addEventListener("change",e=>{cursor=e.target.value;apply()});setInterval(updateWorldClock,1000);updateWorldClock();
fullscreenToggle?.addEventListener("click",async e=>{e.stopPropagation();try{if(!document.fullscreenElement){await document.documentElement.requestFullscreen();fullscreenToggle.textContent="×";fullscreenToggle.setAttribute("aria-label","Exit fullscreen")}else{await document.exitFullscreen();fullscreenToggle.textContent="⛶";fullscreenToggle.setAttribute("aria-label","Enter fullscreen")}}catch{}});
document.addEventListener("fullscreenchange",()=>{if(fullscreenToggle){const on=!!document.fullscreenElement;fullscreenToggle.textContent=on?"×":"⛶";fullscreenToggle.setAttribute("aria-label",on?"Exit fullscreen":"Enter fullscreen")}});
const clock=$("#clock");setInterval(()=>clock.textContent=new Date().toLocaleTimeString([],{hour12:false}),1000);
if(volume&&audio){const v=$("#volumeValue"),sync=()=>{const p=+volume.value;audio.volume=p/100;volume.style.setProperty("--volume",p+"%");v.textContent=p+"%";if(setupVolume)setupVolume.value=p;if($("#setupVolumeValue"))$("#setupVolumeValue").textContent=p+"%"};volume.oninput=sync;setupVolume&&(setupVolume.oninput=()=>{volume.value=setupVolume.value;sync()});volumeToggle.onclick=()=>{audio.muted=!audio.muted;volumeToggle.setAttribute("aria-label",audio.muted?"Unmute music":"Mute music")};sync()}
audio.addEventListener("ended",()=>{index=(index+1)%tracks.length;render();audio.play().catch(()=>{})});audio.addEventListener("play",()=>{wave.classList.remove("paused");pause?.setAttribute("aria-label","Pause music");if(pause)pause.textContent="Ⅱ"});audio.addEventListener("pause",()=>{wave.classList.add("paused");pause?.setAttribute("aria-label","Play music");if(pause)pause.textContent="▶"});audio.addEventListener("timeupdate",()=>{const s=Math.floor(audio.currentTime);$("#musicTime").textContent=String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")});
if("IntersectionObserver"in window){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");o.unobserve(e.target)}}),{threshold:.08});$$(".reveal").forEach((e,i)=>{e.style.setProperty("--delay",Math.min(i*45,250)+"ms");o.observe(e)})}else $$(".reveal").forEach(e=>e.classList.add("visible"));
if(matchMedia("(pointer:fine)").matches){const d=$(".cursor-dot"),r=$(".cursor-ring"),g=$(".cursor-glow");let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;onmousemove=e=>{x=e.clientX;y=e.clientY;d.style.left=x+"px";d.style.top=y+"px";g.style.left=x+"px";g.style.top=y+"px"};(function f(){rx+=(x-rx)*.14;ry+=(y-ry)*.14;r.style.left=rx+"px";r.style.top=ry+"px";requestAnimationFrame(f)})();$$(".magnetic").forEach(e=>{e.onmousemove=a=>{const q=e.getBoundingClientRect();e.style.transform="translate("+((a.clientX-q.left-q.width/2)*.06)+"px,"+((a.clientY-q.top-q.height/2)*.06)+"px)"};e.onmouseleave=()=>e.style.transform=""})}
const av=$("#avatarWrap");if(av&&matchMedia("(pointer:fine)").matches){av.onmousemove=e=>{const q=av.getBoundingClientRect();av.style.transform="perspective(800px) rotateX("+((e.clientY-q.top-q.height/2)*-.08)+"deg) rotateY("+((e.clientX-q.left-q.width/2)*.08)+"deg)"};av.onmouseleave=()=>av.style.transform=""}
onkeydown=e=>{if(e.key==="Escape"&&setup.classList.contains("open"))closeSetup()};$$('a[href^="#"]').forEach(a=>a.onclick=e=>{const t=$(a.getAttribute("href"));if(t){e.preventDefault();t.scrollIntoView({behavior:"smooth"})}});
build();render();apply();if(pause&&audio.paused)pause.textContent="▶";
});